
# Introduction

Because of the heterogeneous nature of pathologic lung processes, studies of disease progression and treatment are complex. Longitudinal studies are advantageous in that normal between-patient variability is minimized. However, many of the longitudinal pulmonary studies conducted to date have been restricted to whole-lung spirometry assessments for evaluation of lung function, with imaging being rapidly adopted owing to its increased spatial sensitivity.

Spirometry is the standard protocol for evaluating lung function because of its low cost, noninvasive nature, and wide availability. Longitudinal spirometry studies have explored such respiratory pathologies as the effects of smoking [@Burchfiel:1995aa;@Kanner:1999aa], asthma [@Sears:2003aa], pollution [@Schultz:2016aa], allergen skin test reactivity [@Langley:2005aa], systemic sclerosis [@Greenwald:1987aa], coal mining [@Love:1982aa], asbestos exposure [@Rom:1992aa], and respiratory syndromes [@Sherman:1992aa].

Two major drawbacks of spirometry, however, are its inability to characterize the spatial distribution of ventilation and its insensitivity to changes in the lungs over short periods of time, thus motivating the development of imaging technology [@Vestbo:2008aa] that can be used independently or in conjunction with spirometry. Computed tomography (CT) has been used extensively to monitor disease progression and treatment response in chronic obstructive pulmonary disease (COPD) [@Ohara:2008aa] and  investigate the progression of emphysema in patients with COPD and alpha-1 antitrypsin deficiency [@Dirksen:1999aa]. Other longitudinal studies have assessed the correlation between CT measurements in the lungs of smokers and forced expiratory volume in 1 second (FEV1) [@Remy-Jardin:2002aa], investigated CT densitometry to detect emphysema progression in patients with alpha-1 antitrypsin deficiency [@Stolk:2003aa;@Parr:2008aa], evaluated the impact of exacerbations and other factors on COPD progression through CT measurements [@Stolk:2007aa;@Tanabe:2011aa], and used high-resolution CT to assess smoking-induced lung density changes [@Soejima:2000aa].

More recently, studies have shown that hyperpolarized helium-3 (3He) magnetic resonance imaging (MRI) has great potential to visualize ventilation defects in the lungs [@Lange:1999aa], with additional potential for computational analysis [@Tustison:2010aa;@Tustison:2011aa;@Kirby:2012aa]. Several advantages are encouraging for the use of 3He MRI over CT. For example, a recent study of pulmonary function as assessed by FEV1 and diffusing capacity of the lung for carbon monoxide found a stronger correlation between pulmonary function and 3He MRI compared with pulmonary function and CT [@Ley:2004aa]. Although 3He MRI longitudinal studies are not as numerous, they have shown great potential, as exemplified by Kirby et al, who investigated COPD progression in ex-smokers compared with healthy volunteers [@Kirby:2010aa].

In order to perform analysis on 3He MRI longitudinal data, the images have to first be spatially normalized to a common reference space, also known as a template or atlas. Such templates are common in the neuroimaging community, although they are found less frequently in the pulmonary research literature. One of the earliest and most widely used templates was the Talaraich atlas, created by Dr. Jean Talairach (a French neurosurgeon), who identified landmarks on the postmortem histologic sections of a 60-year-old French woman to define a universal, stereotactic cerebral space. The utility of a standardized anatomical coordinate system has prompted additional work, such as the publicly available Montreal Neurological Institute brain template [@Collins:1994aa], which is an average of hundreds of adult brain MR images all registered to the Talaraich atlas. Following template construction, statistical analyses can be applied so that biological processes, such as the magnitude of a local neuroresponse to a prescribed stimuli, can be assessed [@Smith:2004aa].

In this article, a similar approach to that described in the neuroimaging example above, was applied to a novel study of patients with cystic fibrosis (CF) treated with a modulator of the mutational defect in CF. Clinical findings of improved lung ventilation with treatment were published in this cohort with CF based on hyperpolarized 3He gas imaging [@Altes:2012aa]. These data are summarized here to illustrate the innovative longitudinal aspects of this pulmonary analysis; the images were initially brought into anatomical alignment via a robust template building strategy, and then voxelwise regression over the time course was used to determine correlative regions with the simplified treatment hypothesis.
